// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2HIbQezbp1ITkSfOK15MalMWaN36biW4',
    appId: '1:306644224408:web:7af119d8628355b45d03ed',
    messagingSenderId: '306644224408',
    projectId: 'webrtc-test-e9f72',
    authDomain: 'webrtc-test-e9f72.firebaseapp.com',
    storageBucket: 'webrtc-test-e9f72.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE6M3xVRSTb9zwLScNCsvDpp1kEe1sQ40',
    appId: '1:306644224408:android:e1cdf9d5b419b7f45d03ed',
    messagingSenderId: '306644224408',
    projectId: 'webrtc-test-e9f72',
    storageBucket: 'webrtc-test-e9f72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrKt7AXSmy5SgL79aofhB42tuKw0bG2gg',
    appId: '1:306644224408:ios:c7ff31846c75d2605d03ed',
    messagingSenderId: '306644224408',
    projectId: 'webrtc-test-e9f72',
    storageBucket: 'webrtc-test-e9f72.appspot.com',
    iosClientId: '306644224408-u3pt5sb4v70lj42a6a4oa557o781iim1.apps.googleusercontent.com',
    iosBundleId: 'com.sam.testFlutterWebrtc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrKt7AXSmy5SgL79aofhB42tuKw0bG2gg',
    appId: '1:306644224408:ios:c7ff31846c75d2605d03ed',
    messagingSenderId: '306644224408',
    projectId: 'webrtc-test-e9f72',
    storageBucket: 'webrtc-test-e9f72.appspot.com',
    iosClientId: '306644224408-u3pt5sb4v70lj42a6a4oa557o781iim1.apps.googleusercontent.com',
    iosBundleId: 'com.sam.testFlutterWebrtc',
  );
}
